"""Utilities for scaffolding sensors and creators."""

from pathlib import Path

def scaffold(name: str, dest: Path | str = '.') -> Path:
    """Create a basic folder under ``dest`` with the given ``name``."""
    dest_path = Path(dest) / name
    dest_path.mkdir(parents=True, exist_ok=True)
    (dest_path / '__init__.py').write_text('# generated by forge')
    return dest_path
