name: Arena Nightly
on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  arena:
    runs-on: ubuntu-latest
    env:
      GH_BOT_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -e .[dev]
      - run: python arena.py
