name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install
        run: pip install -e .[dev,explore]
      - name: Guard generated.eidos size
        run: |
          bytes=$(stat --printf="%s" generated.eidos)
          if [ "$bytes" -gt 204800 ]; then
            echo "generated.eidos too big ($bytes bytes)"; exit 1;
          fi
      - run: yamllint .github/workflows todo
      - name: Run tests
        env:
          GH_BOT_TOKEN: ${{ secrets.GH_BOT_TOKEN || '' }}
        run: pytest -q
