name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install
        run: pip install -e .[dev]
      - name: Run tests
        env:
          GH_BOT_TOKEN: ${{ secrets.GH_BOT_TOKEN || '' }}
        run: pytest -q
