name: Daily Run
on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'
jobs:
  set-token:
    uses: ./.github/workflows/set-token.yml
    secrets: inherit
  run:
    needs: set-token
    runs-on: ubuntu-latest
    env:
      GH_BOT_TOKEN: ${{ needs.set-token.outputs.token }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: python mae_watcher.py --owner bmparent --repo little-eidos-playground
      - run: python emergent_intelligence.py
