name: Prune Weekly
on:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  prune:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install
        run: pip install -e .[dev]
      - name: Prune branches
        run: python -m agents.branch_pruner --days 21 --keep 8
