name: Daily
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install
        run: pip install -e .[dev]
      - name: Run intelligence
        run: python emergent_intelligence.py
      - name: Evaluate MAE
        run: python -m agents.mae_watcher
