name: Treasure Hunter

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

env:
  TREASURE_BRANCH: treasure-hunter

jobs:
  hunt:
    runs-on: ubuntu-latest
    timeout-minutes: 55
    steps:
      - name: Checkout repo (no ref hard-coded)
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT_TREASURE }}
          fetch-depth: 0

      - name: Bootstrap / ensure ${{ env.TREASURE_BRANCH }} exists
        shell: bash
        env:
          TREASURE_BRANCH: ${{ env.TREASURE_BRANCH }}
          DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
        run: |
          set -euo pipefail
          echo "Ensuring branch $TREASURE_BRANCH exists..."
          DB="${DEFAULT_BRANCH:-$(git remote show origin | awk '/HEAD branch/ {print $NF}')}"
          echo "Default branch detected: $DB"
          git fetch origin +refs/heads/*:refs/remotes/origin/*
          if git show-ref --verify --quiet refs/remotes/origin/$TREASURE_BRANCH; then
            echo "Branch exists remotely; switching."
            git checkout -B $TREASURE_BRANCH origin/$TREASURE_BRANCH
          else
            echo "Branch missing; creating from $DB."
            git checkout $DB
            git checkout -b $TREASURE_BRANCH
            git push --set-upstream origin $TREASURE_BRANCH
          fi
          git branch -vv

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: pip install -r treasure-hunter/requirements.txt

      - name: Run Treasure Hunter
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GH_PAT_TREASURE: ${{ secrets.GH_PAT_TREASURE }}
        run: python treasure-hunter/hunter/main.py

      - name: Commit & push new treasures (if any)
        shell: bash
        env:
          TREASURE_BRANCH: ${{ env.TREASURE_BRANCH }}
        run: |
          set -euo pipefail
          git config user.name "eidos-bot"
          git config user.email "eidos-bot@users.noreply.github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add -A
            git commit -m "chore(treasure): hourly haul $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "Nothing to commit"
            git push origin HEAD:$TREASURE_BRANCH
          else
            echo "No changes to commit."
          fi
