name: Weekly Visionary
on:
  schedule:
    - cron: '23 4 * * 1'
jobs:
  vision:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with: {ref: main}
      - uses: actions/setup-python@v5
        with: {python-version: '3.x'}
      - name: Install repo
        run: pip install -e .[dev]
      - name: Run visionary
        env:
          GH_BOT_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
        run: python agents/visionary.py
