name: Weekly Tuner
on:
  schedule:
    - cron: '31 4 * * 0'
jobs:
  tune:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with: {ref: main}
      - uses: actions/setup-python@v5
        with: {python-version: '3.x'}
      - name: Install repo
        run: pip install -e .[dev]
      - name: Run tuner
        run: python agents/tuner.py
      - name: Commit tuned params
        run: |
          if git diff --quiet; then
            echo "No tuning changes"; exit 0; fi
          git add tuning.json memory.json
          git commit -m "chore: weekly tuner update"
          git push origin HEAD:main
