---
name: Weekly Hyper-param Tuner
'on':
  schedule:
    - cron: '0 4 * * 0'
  workflow_dispatch: {}
jobs:
  tune:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: pip install -e .[dev]
      - run: python -m agents.tuner
      - name: Commit & push tuned params
        run: |
          if git diff --quiet; then exit 0; fi
          git commit -am "chore: weekly tuned hyper-params"
          git push origin HEAD:main
